# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
