# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0003_auto_20180226_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
