# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0004_estateagent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estateagent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
