# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0005_auto_20180226_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
