# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import estate_agent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0006_estateagent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateagent',
            name='address2',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[estate_agent.validators.validate_location]),
        ),
    ]
