# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_agent', '0007_auto_20180227_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateagent',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
