# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0008_estateagent_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estateagent',
            name='owner',
        ),
    ]
