# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0009_remove_estateagent_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateagent',
            name='address2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
