# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate_agent.EstateAgent'),
        ),
    ]
