# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180530_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='estate',
        ),
        migrations.AddField(
            model_name='user',
            name='testfield',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
    ]
