# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0008_estateagent_owner'),
        ('accounts', '0006_auto_20180530_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='estate_agent.EstateAgent'),
            preserve_default=False,
        ),
    ]
