# Generated by Django 2.2.5 on 2019-09-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estate_agent.EstateAgent'),
        ),
    ]
