# Generated by Django 2.2.5 on 2019-09-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190920_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_agent.EstateAgent'),
        ),
    ]
