# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate_agent', '0008_estateagent_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('street_name', models.CharField(max_length=120)),
                ('property_type', models.CharField(max_length=120)),
                ('number_rooms', models.IntegerField()),
                ('description', models.TextField(blank=True, help_text='Enter details of the property', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estate_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_agent.EstateAgent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
