# Generated by Django 2.2.5 on 2019-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
